# Generated by Django 4.2.4 on 2023-11-14 11:31

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_remove_movie_category_alter_movie_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='movie_title',
        ),
        migrations.RemoveField(
            model_name='hot_thrills',
            name='update',
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_portrait',
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_1',
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_2',
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_3',
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_4',
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_5',
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_6',
            field=models.URLField(max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='movie_title', unique=True),
        ),
        migrations.AlterField(
            model_name='trending',
            name='poster_landscape',
            field=models.URLField(max_length=900),
        ),
    ]
