# Generated by Django 4.2.4 on 2023-11-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0005_rename_title_movie_movie_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='hot_thrills',
            options={'verbose_name_plural': 'Hot Slideshow'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'Add movies'},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name_plural': 'Recommanded posters'},
        ),
        migrations.AlterModelOptions(
            name='trending',
            options={'verbose_name_plural': 'Trending Silder'},
        ),
    ]
