# Generated by Django 4.2.4 on 2023-11-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0007_hot_thrills_name_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='update',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
