# Generated by Django 4.2.4 on 2023-11-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0008_movie_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='update',
            field=models.CharField(default='No Updates', max_length=100),
        ),
    ]
