# Generated by Django 4.2.4 on 2023-11-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0009_alter_movie_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='poster1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_wallpaper', models.ImageField(upload_to='movie_media')),
            ],
            options={
                'verbose_name_plural': 'Recommanded posters 1',
            },
        ),
        migrations.CreateModel(
            name='poster2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_wallpaper', models.ImageField(upload_to='movie_media')),
            ],
            options={
                'verbose_name_plural': 'Recommanded posters 2',
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.CharField(help_text='Ex: Chris hamesworth • Scarllet johnson', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(help_text='Enter the movie description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(help_text='Ex: Mark • David Hammer • Chris Green', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='distibuted_by',
            field=models.CharField(help_text='Ex: Warner Bros. Entertainment • Marvel Studio', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(help_text='Enter the IMDb rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(help_text='Ex: English • Hindi', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_duration',
            field=models.CharField(help_text='Enter the movie duration Ex: 2h 34min', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_grade',
            field=models.CharField(help_text='Ex: U/A 18+', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_match',
            field=models.CharField(help_text='Ex: 67% Match ,Enter only number', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(help_text='Ex: Loki full hd movie download', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_trailler',
            field=models.CharField(help_text='Enter the youtube trailler video id Ex: aR_JzBGdGvM', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(help_text='Ex: 2024'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(help_text='Enter the movie name', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_portrait',
            field=models.URLField(help_text='Enter the movie poster URL Ex: http://...', max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(help_text='Ex: 720p • 1080p • 2160p 60fps', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released_at',
            field=models.DateField(blank=True, help_text=' Ex: 23/09/2021', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_1',
            field=models.URLField(help_text='Enter the Screenshot 1 URL', max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_2',
            field=models.URLField(help_text='Enter the Screenshot 2 URl', max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_3',
            field=models.URLField(help_text='Enter the Screenshot 3 URL', max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_4',
            field=models.URLField(help_text='Enter the Screenshot 4 URL', max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_5',
            field=models.URLField(help_text='Enter the Screenshot 5 URL', max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenshot_6',
            field=models.URLField(help_text='Enter the Screenshot 6 URL', max_length=900),
        ),
        migrations.AlterField(
            model_name='movie',
            name='subtitle',
            field=models.CharField(help_text='Ex: English • Hindi • Spanish', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='update',
            field=models.CharField(default='No Updates', help_text='Ex: Episode 3 Added', max_length=100),
        ),
        migrations.DeleteModel(
            name='poster',
        ),
        migrations.AddField(
            model_name='poster2',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster2_movies', to='detail.movie'),
        ),
        migrations.AddField(
            model_name='poster1',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster1_movies', to='detail.movie'),
        ),
    ]
