# Generated by Django 4.2.4 on 2023-11-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0010_poster1_poster2_alter_movie_cast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='poster3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_wallpaper', models.ImageField(upload_to='movie_media')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster3_movies', to='detail.movie')),
            ],
            options={
                'verbose_name_plural': 'Recommanded posters 3',
            },
        ),
    ]
